ALTER TABLE "budget_labor_costs"
  ADD COLUMN IF NOT EXISTS "store_performance" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "effective_contributor_count" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "cost_structures"
  ADD COLUMN IF NOT EXISTS "sick_maternity_annual_leave" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "severance" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "jjbcj" DOUBLE PRECISION NOT NULL DEFAULT 0;
